# Install roles from the Ansible Galaxy
- src: andrewrothstein.terraform
# renamed apparently - src: geerlingguy.ansible-role-packer
- src: geerlingguy.packer
- src: geerlingguy.git
- src: christiangda.awscli
